version: "3"
services:
  fpm:
    container_name: laravel-fpm
    build: ./php
    volumes:
      - ../:/var/www
      - ./php/postfix:/etc/postfix/sasl
    depends_on:
      - db
    tty: true

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ../Laravel_Forum-B:/usr/local/src/Laravel_Forum-B
    working_dir: /usr/local/src/Laravel_Forum-B
    command: composer install
    tty: true

  node:
    image: node:16.16.0-alpine
    container_name: laravel-node
    volumes:
      - ../Laravel_Forum-B:/usr/local/src/Laravel_Forum-B
    working_dir: /usr/local/src/Laravel_Forum-B
    command: npm install --update-binary --no-shrinkwrap && npm install
    tty: true

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - 8080:80
    volumes:
      - ../:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - fpm
    tty: true

  db:
    image: mysql:5.7
    container_name: laravel-db
    environment:
      MYSQL_DATABASE: forum
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_PASSWORD: pass
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    tty: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=rootpass
    ports:
      - 4040:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
    tty: true
