version: "3"
services:
  hira-chan_app:
    image: hira-chan_app:latest
    container_name: hira-chan_app
    build:
      context: ..
      dockerfile: ./docker/app/Dockerfile
    user: dev
    volumes:
      - ..:/usr/src/app
    depends_on:
      - hira-chan_mysql
    tty: true

  hira-chan_nginx:
    image: hira-chan_nginx:latest
    container_name: hira-chan_nginx
    build:
      context: ..
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ..:/var/www/hira-chan
      - hira-chan_phpmyadmin-vol:/var/www/phpmyadmin
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - hira-chan_app
      - hira-chan_phpmyadmin
    tty: true

  hira-chan_mysql:
    image: hira-chan_mysql:latest
    container_name: hira-chan_mysql
    build:
      context: ..
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: forum
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_PASSWORD: pass
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    tty: true

  hira-chan_phpmyadmin:
    image: hira-chan_phpmyadmin:latest
    container_name: hira-chan_phpmyadmin
    build:
      context: ..
      dockerfile: ./docker/phpmyadmin/Dockerfile
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=hira-chan_mysql
      - PMA_USER=root
      - PMA_PASSWORD=rootpass
      - PMA_VERBOSE=phpmyadmin
      - PMA_PORT=3306
    volumes:
      - hira-chan_phpmyadmin-vol:/var/www/html
    depends_on:
      - hira-chan_mysql
    tty: true

volumes:
  hira-chan_phpmyadmin-vol:
