services:
  prometheus:
    image: prom/prometheus:main
    ports:
      - 9090:9090
    volumes:
      - ../prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
    restart: always
  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - 9113:9113
    command:
      - '--nginx.scrape-uri=http://192.168.0.10:8080/stub_status'
    restart: always
