name: Laravel

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.0"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install
      - name: Compile
        run: npm run prod
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mysql --protocol=tcp -h localhost -P 3306 -u root -ppassword -e "CREATE DATABASE main"
          mysql --protocol=tcp -h localhost -P 3306 -u root -ppassword -e "CREATE DATABASE forum"
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_DATABASE: main
          DB_DATABASE_KEIZIBAN: forum
          DB_PASSWORD: password
        run: vendor/bin/phpunit --testdox
      - name: git status
        run: git status
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Diff
        uses: technote-space/get-diff-action@v5
        with:
          FILES: |
            .github/workflows
      - name: notify diff
        if: contains(env.GIT_DIFF, '.github/workflows')
        run: echo ${{ env.GIT_DIFF }}
