# プルリクのマージで実行
#
# on:
#   pull_request:
#     branches:
#       - develop
#     types: [closed]
#
# jobs:
#   tag:
#     runs-on: ubuntu-latest
#     if: github.event.pull_request.merged == true

name: Slack Notification

on: push

jobs:
  slackNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "channel": "${{ secrets.SLACK_CHANNEL_ID }}",
              "attachments": [
                {
                  "fallback": "Confirm merge Pull-Requests",
                  "color": "#2eb886",
                  "text": "test",
                  "fields": [
                    {
                      "title": "title-1",
                      "value": "this is value-1",
                      "short": true
                    },
                    {
                      "title": "title-2",
                      "value": "this is value-2",
                      "short": true
                    },
                    {
                      "title": "title-3",
                      "value": "this is value-3",
                      "short": false
                    },
                    {
                      "title": "title-4",
                      "value": "this is value-4",
                      "short": true
                    },
                    {
                      "title": "title-5",
                      "value": "this is value-5",
                      "short": true
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
