# プルリクのマージで実行
#
# on:
#   pull_request:
#     branches:
#       - develop
#     types: [closed]
#
# jobs:
#   tag:
#     runs-on: ubuntu-latest
#     if: github.event.pull_request.merged == true

name: Slack Notification

on: push

jobs:
  slackNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "channel": "${{ secrets.SLACK_CHANNEL_ID }}",
              "attachments": [
                {
                  "fallback": "Confirm merge Pull-Requests",
                  "color": "good",
                  "pretext": "<!channel>\n*プルリクエストがマージされました*\n`git pull`を実行してローカルリポジトリを更新して下さい",
                  "author_name": "${{ github.actor }}",
                  "author_icon": "${{ github.event.sender.avatar_url }}",
                  "fields": [
                    {
                      "title": "Pull request Title",
                      "value": "${{ github.event.pull_request.title }}",
                      "short": false
                    },
                    {
                      "title": "Number",
                      "value": "${{ github.event.pull_request.number }}",
                      "short": true
                    },
                    {
                      "title": "Event Type",
                      "value": "${{ github.event_name }}",
                      "short": true
                    },
                    {
                      "title": "title-4",
                      "value": "this is value-4",
                      "short": false
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
