# プルリクのマージで実行
#
# on:
#   pull_request:
#     branches:
#       - master
#     types: [closed]
#
# jobs:
#   tag:
#     runs-on: ubuntu-latest
#     if: github.event.pull_request.merged == true

name: Slack Notification

on: push

jobs:
  slackNotification:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2

      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
